# vCrates - Main configuration
# By VulpineFriend87

storage:

  # H2 or MYSQL
  # H2: creates a local h2 database in a file
  # MYSQL: uses an existing mysql database
  method: H2

  # These settings are only required for MYSQL (they will be ignored if method is H2)
  host: localhost
  port: 3306
  database: vcrates
  username: vcrates
  password: vcrates

# Placeholders
placeholders:
  leaderboard:
    entry: "&7%rank%° &9%player% &7- &9%value%"
    empty: "&7-° &9--- &7- &9---"

# Logging
# Possible values: INFO, WARN, ERROR
# INFO: Logs everything
# WARN: Only logs warnings and errors
# ERROR: Only logs errors
logging_level: INFO